#!/bin/sh

set -e

playerName=''
playerAttack=0
playerDefend=0
playerLuck=0
playerMonster0=''
playerMonster1=''
playerMonster2=''
playerMonster3=''

rival=''

inc() {
  echo "$1 + 1" | bc
}

dec() {
  echo "$1 - 1" | bc
}

getmonster() {
  while [ -z "$monster" ];
  do
  num=$(echo $RANDOM % $(wc -l .monsters | awk '{print $1}') | bc)
  num=$(dec "$num")
  monster=$(head -n "$num" .monsters| tail -n1 | awk '{print $1}')
  done
  echo "$monster"
}

getmonsterSound() {
  sound=$(grep "$1 " .monsters | awk '{print $2}')
  echo "$sound"
}

# store for dialog
tmp=$(mktemp)
exec 3>"$tmp" # keep file descriptor open


intro() {
rivalMonster=$(getmonster)

#get player name
dialog --inputbox 'What is your name?' 10 25 'San' 2> "$tmp"
playerName=$(cat "$tmp")

# set rival name
dialog --inputbox 'What is the name of your rival?' 10 25 'Tanner' 2> "$tmp"
rival=$(cat "$tmp")

dialog --pause 'Your adventure is about to begin...' 10 25 5

dialog --msgbox "Mom: Hello, $playerName! Today's the big day!" 10 25
dialog --msgbox "Mom: Today you become a Master, $playerName!" 10 25
dialog --msgbox "Mom: Your first monster should be hatching any moment now, $playerName!" 10 25
dialog --msgbox "Mom: What kind did you end up getting anyway, $playerName?" 10 25

while [ -z "$playerMonster0" ];
do
dialog --radiolist 'Oh, I got a...' 10 25 20 \
$(getmonster) '' 1 \
$(getmonster) '' 2 \
$(getmonster) '' 3 \
$(getmonster) '' 4 \
2> "$tmp"
playerMonster0=$(cat "$tmp")
done

unhatched='t'

dialog --msgbox "Mom: Wow, $playerName! Good choice!" 10 25

dialog --msgbox "Mom: You should come downstairs soon, you don't want to miss it hatching." 10 25
dialog --msgbox "(Mom leaves the room.)" 10 25

room='homeBedroom'
}

homeBedroom() {
  dialog --radiolist "$playerName's bedroom:" 10 25 20 \
  'A bed' '' 1 \
  'A PC' '' 2 \
  'A training magazine' '' 3 \
  'Exit to lounge room' '' 4 \
  'Quit' '' 5 \
  2>"$tmp"
  case $(cat "$tmp") in
    'A bed')
      dialog --msgbox "$playerName restfully sleeps" 10 25
      ;;
    'A PC')
      dialog --msgbox 'The only thing of interest is a card game.' 10 25
      ;;
    'A training magazine')
      dialog --msgbox 'You much prefer the ads for rare monsters over the articles.' 10 25
      dialog --msgbox 'Too bad they are so expensive.' 10 25
      ;;
    'Exit to lounge room')
      room='homeLounge'
      ;;
    'Quit')
      room='quit'
      ;;
  esac
}

homeLounge() {
  if [ "$unhatched" = 't' ]; then
    unhatched='f'
    dialog --msgbox 'An egg lies in the middle of the room.' 10 25
    dialog --msgbox 'It shakes.' 10 25
    sound=$(getmonsterSound "$playerMonster0")
    dialog --msgbox "With a low $sound a $playerMonster0 tumbles onto the ground." 10 25
    playerAttack='1'
  else
    dialog --radiolist "$playerName's lounge room:" 10 25 20 \
    'Mom' '' 1 \
    "$playerMonster0" '' 2 \
    'A TV' '' 3 \
    'Door to outside' '' 4 \
    'Quit' '' 5 \
    2>"$tmp"
    case $(cat "$tmp") in
      'Mom')
        dialog --msgbox "Mom: You should be getting along to the graduation ceremony, $playerName. At the castle." 10 25
        ;;
      "$playerMonster0")
        sound=$(getmonsterSound "$playerMonster0")
        dialog --msgbox "The $playerMonster0 looks at you with wide eyes, and lets out a cute little $sound." 10 25
        ;;
      'A TV')
        dialog --msgbox 'The president is on TV, raving about some new dragon sanctuary. He would, he caught a dragon.' 10 25
        ;;
      'Door to outside')
        dialog --msgbox "The $playerMonster0 follows you." 10 25
        room='hometownSquare'
        ;;
      'Quit')
        room='quit'
        ;;
    esac
  fi
}

fight() {
  soundA=$(getmonsterSound "$1")
  soundB=$(getmonsterSound "$2")
  dialog --msgbox "The $1 makes a threatening $soundA" 10 25
  dialog --msgbox "The $2 responds with a $soundB" 10 25
  while [ -z "$win" ];
  do
    attack=$(echo "$playerAttack + $playerLuck" | bc)
    defend=$(echo "$playerDefend + $playerLuck" | bc)
    attack2=$(echo "$attack / 2" | bc)
    defend2=$(echo "$defend / 2" | bc)
    dialog --msgbox "The $1 attacks: $attack" 10 25
    dialog --msgbox "The $2 defends: $defend2" 10 25
    if [ "$attack" -gt "$defend2" ]; then
      dialog --msgbox "The attack succeeds!" 10 25
      playerLuck=$(inc "$playerLuck")
    else
      dialog --msgbox "The attack fails!" 10 25
    fi

    dialog --msgbox "The $2 attacks: $attack2" 10 25
    dialog --msgbox "The $1 defends: $defend" 10 25
    if [ "$attack2" -gt "$defend" ]; then
      dialog --msgbox "The attack succeeds!" 10 25
    else
      dialog --msgbox "The attack fails!" 10 25
      playerLuck=$(inc "$playerLuck")
    fi
    if [ "$playerLuck" -eq 10 ]; then
      win='t'
    fi
  done
}

hometownSquare() {
  if [ -z "$visitedHometownSquare" ]; then
    dialog --msgbox "$rival: Hey! Eggface!" 10 25
    dialog --msgbox "$rival appears to have been waiting for you. With his $rivalMonster!" 10 25
    dialog --msgbox "$rival: I can beat you! Hand over your $playerMonster0 or fight!" 10 25
    fight "$playerMonster0" "$rivalMonster"
    dialog --msgbox "$rival: No fair! You cheated!" 10 25
    dialog --msgbox "($rival runs away)" 10 25
    playerAttack=$(inc "$playerAttack")
    playerLuck='0'
    visitedHometownSquare='t'
  else
    dialog --radiolist "Hometown: Square:" 10 25 20 \
    'Music stage' '' 1 \
    'Balloon clown' '' 2 \
    'Path to the castle' '' 3 \
    'Quit' '' 4 \
    2>"$tmp"
    case $(cat "$tmp") in
      'Music stage')
        sound=$(getmonsterSound "$playerMonster0")
        dialog --msgbox "Your $playerMonster0 seems to like the music. It taps its paw, $sound to itself." 10 25
        ;;
      'Balloon clown')
        dialog --msgbox "The clown hands you a balloon in the shape of a $playerMonster0"
        ;;
      'Path to the castle')
        dialog --msgbox 'It is a long winding path, uphill.' 10 25
        room='outsideCastle'
        ;;
      'Quit')
        room='quit'
        ;;
    esac
  fi
}

# check for a savefile
if [ -f '.save' ]; then
  . '.save'
else
  intro
fi

# tick the game
while [ "$room" != 'quit' ];
do
  $room
done

# save
echo "playerName='$playerName'" > '.save'
echo "playerAttack='$playerAttack'" >> '.save'
echo "playerDefend='$playerDefend'" >> '.save'
echo "playerLuck='$playerLuck'" >> '.save'
echo "playerMonster0='$playerMonster0'" >> '.save'

rm "$tmp"
