#!/bin/sh

set -e

playerName=''
playerAttack=0
playerDefend=0
playerLuck=0
playerMonster0=''
playerMonster1=''
playerMonster2=''
playerMonster3=''

rival=''

inc() {
  echo "$1 + 1" | bc
}

dec() {
  echo "$1 - 1" | bc
}

getmonster() {
  num=$(echo $RANDOM % $(wc -l .monsters | awk '{print $1}') | bc)
  num=$(dec "$num")
  monster=$(head -n "$num" .monsters| tail -n1)
  echo "$monster"
}

rivalMonster=$(getmonster)

# store for dialog
tmp=$(mktemp)
exec 3>"$tmp" # keep file descriptor open

#get player name
dialog --inputbox 'What is your name?' 10 25 'San' 2> "$tmp"
playerName=$(cat "$tmp")

# set rival name
dialog --inputbox 'What is the name of your rival?' 10 25 'Tanner' 2> "$tmp"
rival=$(cat "$tmp")

dialog --pause 'Your adventure is about to begin...' 10 25 5

dialog --msgbox "Mom: Hello, $playerName!    Today's the big day!" 10 25
dialog --msgbox "Mom: Today you become a Master, $playerName!" 10 25
dialog --msgbox "Mom: Your first monster should be hatching any moment now, $playerName!" 10 25
dialog --msgbox "Mom: What kind did you end up getting anyway, $playerName?" 10 25

dialog --radiolist 'Oh, I got a...' 10 25 20 \
$(getmonster) '' 1 \
$(getmonster) '' 2 \
$(getmonster) '' 3 \
$(getmonster) '' 4 \
2> "$tmp"

playerMonster0=$(cat "$tmp")
unhatched='t'

if [ -z "$playerMonster0" ]; then
  dialog --msgbox "Mom: You forgot, $playerName?" 10 25
  dialog --msgbox 'Mom: That is okay. I did not.' 10 25
  playerMonster0=$(getmonster)
else
  dialog --msgbox "Mom: Wow, $playerName! Good choice!" 10 25
fi

dialog --msgbox "Mom: You should come downstairs soon, you don't want to miss it hatching." 10 25
dialog --msgbox "(Mom leaves the room.)" 10 25

room='homeBedroom'

homeBedroom() {
  dialog --radiolist "$playerName's bedroom:" 10 25 20 \
  'A bed' '' 1 \
  'A PC' '' 2 \
  'A training magazine' '' 3 \
  'Exit to lounge room' '' 4 \
  'Quit' '' 5 \
  2>"$tmp"
  case $(cat "$tmp") in
    'A bed')
      dialog --msgbox "$playerName restfully sleeps" 10 25
      ;;
    'A PC')
      dialog --msgbox 'The only thing of interest is a card game.' 10 25
      ;;
    'A training magazine')
      dialog --msgbox 'You much prefer the ads for rare monsters over the articles.' 10 25
      dialog --msgbox 'Too bad they are so expensive.' 10 25
      ;;
    'Exit to lounge room')
      room='homeLounge'
      ;;
    'Quit')
      room='quit'
      ;;
  esac
}

homeLounge() {
  if [ "$unhatched" = 't' ]; then
    unhatched='f'
    dialog --msgbox 'An egg lies in the middle of the room.' 10 25
    dialog --msgbox 'It shakes.' 10 25
    dialog --msgbox "With a low growl a $playerMonster0 tumbles onto the ground." 10 25
  else
    dialog --radiolist "$playerName's lounge room:" 10 25 20 \
    'Mom' '' 1 \
    "$playerMonster0" '' 2 \
    'A TV' '' 3 \
    'Door to outside' '' 4 \
    'Quit' '' 5 \
    2>"$tmp"
    case $(cat "$tmp") in
      'Mom')
        dialog --msgbox "Mom: You should be getting along to the graduation ceremony, $playerName. At the castle." 10 25
        ;;
      "$playerMonster0")
        dialog --msgbox "The $playerMonster0 looks at you with wide eyes, and lets out a cute little sound." 10 25
        ;;
      'A TV')
        dialog --msgbox 'The president is on TV, raving about some new dragon sanctuary. He would, he caught a dragon.' 10 25
        ;;
      'Door to outside')
        room='hometownSquare'
        ;;
      'Quit')
        room='quit'
        ;;
    esac
  fi
}

# tick the game
while [ "$room" != 'quit' ];
do
  $room
done

rm "$tmp"
